[package]
name = "cubixwm"
edition.workspace = true
license.workspace = true
version.workspace = true
authors.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "cubixwm"
path = "src/main.rs"

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["clock"] }
smithay = { version = "0.7", default-features = false, features = ["backend_winit", "renderer_glow", "wayland_frontend", "desktop", "xwayland"] }
