[package]
name = "cubixwm"
edition.workspace = true
license.workspace = true
version.workspace = true
authors.workspace = true

[features]
default = []
tty-backend = ["dep:drm", "dep:rustix", "smithay/backend_session_libseat", "smithay/backend_udev"]

[lib]
path = "src/lib.rs"

[[bin]]
name = "cubixwm"
path = "src/main.rs"

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["clock"] }
drm = { version = "0.14", optional = true }
rustix = { version = "1", features = ["fs"], optional = true }
smithay = { version = "0.7", default-features = false, features = ["backend_winit", "renderer_glow", "wayland_frontend", "desktop", "xwayland"] }
wayland-protocols = { version = "0.32", features = ["server"] }
